Prevent Errors when transition is called after Component is unloaded
robguy21/js-async-state-machine pull request #6
Opened 2019-07-31 14:09 UTC by sscholle

Sometimes a transition may be triggered when the state is RESET (null) - add check for this

2019-08-01 08:12 UTC, sscholle commented
@robguy21 you're up!

2019-08-26 13:01 UTC, robguy21 requested changes

2019-08-26 13:01 UTC, robguy21 commented on src/machine.js
> +      return false;
this breaks the expected return- you should throw an error

2019-08-26 13:01 UTC, robguy21 commented on src/machine.js
> +    if (!transition) {
this should be handled in `verifyEdge`, you should rather check that `transition` supports a `.toString()` call

2019-08-26 13:01 UTC, robguy21 commented on src/machine.js
> +      return false;
rather throw

2019-08-26 13:01 UTC, robguy21 commented on src/machine.js
> +      this.log('Invalid State - unable get Edges for Transistion');
log what `this.#state` is - it's super useful for debugging

2019-08-26 13:02 UTC, robguy21 requested changes
Also please include tests

2019-08-27 09:36 UTC, robguy21 approved these changes

2019-08-29 10:07 UTC, merged